version: 2.1
orbs:
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: ./gradlew check
      - store_test_results:
          path: build/test-results
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.gradle/caches
      - store_artifacts:
          path: build/reports
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - aws-elastic-beanstalk/setup:
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          aws-region: ca-central-1
      - checkout
      - run:
          name: Build JAR
          command: ./gradlew bootJar
      - aws-elastic-beanstalk/deploy:
          app-name: sakanu
          env-name: sakanu-prod
          version-label: v$(date +%s)
          region: us-east-1
          jar-path: build/libs/sakanu.jar
workflows:
  build-and-test:
    jobs:
      - test-java
      - deploy:
          requires:
            - test-java