version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: ./gradlew check
      - store_test_results:
          path: build/test-results
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.gradle/caches
      - store_artifacts:
          path: build/reports
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - eb/setup
      - checkout
      - run:
          name: Build JAR
          command: ./gradlew bootJar
      - run:
          name: Deploy to Elastic Beanstalk
          command: |
            eb create sakanu-prod --elb-type application --region ca-central-1 --profile default
            eb deploy sakanu-prod --label v$(date +%s) --region ca-central-1 --profile default
workflows:
  build-and-test:
    jobs:
      - test-java
      - eb/deploy:
          requires:
            - test-java