version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - aws-cli/setup
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: ./gradlew check
      - store_test_results:
          path: build/test-results
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.gradle/caches
      - store_artifacts:
          path: build/reports
      - run:
          name: Build JAR
          command: ./gradlew bootJar
      - run:
          name: Upload JAR to S3
          command: aws s3 cp build/libs/sakanu.jar s3://sakanu-deploy/sakanu.jar
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - aws-cli/setup
      - checkout
      - run:
            name: Create application version
            command: |
              aws elasticbeanstalk create-application-version --application-name sakanu --version-label v$(date +%s) --source-bundle S3Bucket="sakanu-deploy",S3Key="sakanu.jar"
      - run:
          name: Deploy to Elastic Beanstalk
          command: |
            aws elasticbeanstalk update-environment --application-name sakanu \
            --option-settings Namespace=aws:elasticbeanstalk:application:environment,OptionName=APP_UI_URL,Value=$APP_UI_URL \
            --environment-name sakanu-prod --version-label v$(date +%s)
workflows:
  build-and-test:
    jobs:
      - test-java
      - deploy:
          requires:
            - test-java